substitutions:
  _ETCD_VERSION: "3.4.3"
steps:
- id: build
  name: 'gcr.io/jumperfly/rpm-builder'
  env:
    - RPM_VERSION=${_ETCD_VERSION}
    - RPM_SPEC=etcd.spec
- id: upload
  name: gcr.io/cloud-builders/gcloud
  env:
    - ETCD_VERSION=${_ETCD_VERSION}
  entrypoint: 'bash'
  args: ['bintray-upload.sh']
